### ISSUE TITLE
How do I get the outlined Icons back?

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/ionicons#550]
I use the font icon set with `<i class="icon ion-ios-chatboxes-outline"></i>` but I do not see anything. When I remove the `-outline` the icon appears.

Do I have to add something else?

**Comment by Nicolaidavies** [comment]
@muuvmuuv It seems the `-outline` icons aren't in ionicons v4. 

A search on [ionicons.com v4](https://ionicons.com/) for "cog" only returns one cog icon and not two as in [version 3](https://ionicframework.com/docs/ionicons/). 

I'm guessing they are moving away from using the `-outline` styled icons for version 4 of ionic.

**Comment by muuvmuuv** [comment]
Sad to hear. But it would be very nice to have them! Because I‘m missing some company logos in v3 and I don‘t want to use a ‚older‘ Version. Maybe they can add a generator. So we can compile them by ourself?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by muuvmuuv** [comment]
Fixed it by installing `npm i ionicons-npm` (https://github.com/DominicTobias/ionicons) old v2 icon pack. Then I added this into my scss:

```scss
// Ionicons v2 custom

@import '../../../node_modules/ionicons-npm/scss/ionicons-variables';
$ionicons-font-family: 'IoniconsV2'; // added `V2` at the end
$ionicons-prefix: ion-alt-; // added an alt suffix to the prefix

@font-face {
  font-family: $ionicons-font-family;
  font-style: normal;
  font-weight: normal;

  // Added a `-v2` suffix
  src: url('#{$ionicons-font-path}/ionicons-v2.eot?v=#{$ionicons-version}');
  src: url('#{$ionicons-font-path}/ionicons-v2.eot?v=#{$ionicons-version}#iefix') format('embedded-opentype'),
  url('#{$ionicons-font-path}/ionicons-v2.ttf?v=#{$ionicons-version}') format('truetype'),
  url('#{$ionicons-font-path}/ionicons-v2.woff?v=#{$ionicons-version}') format('woff'),
  url('#{$ionicons-font-path}/ionicons-v2.svg?v=#{$ionicons-version}#Ionicons') format('svg');
}

.ion {
  display: inline-block;

  font-family: $ionicons-font-family;
  font-style: normal;
  font-variant: normal;
  font-weight: normal;

  line-height: 1;

  text-rendering: auto;
  text-transform: none;

  speak: none;

  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}


@import '../../../node_modules/ionicons-npm/scss/ionicons-icons';
```
