### ISSUE TITLE
"Rotate" icon

### ISSUE THREAD

**Issue by dlipinski** [ionic-team/ionicons#905]
Hi, rotate icon would be just great, thanks

**Comment by danny-englander** [comment]
I was able to do this using this code:

```scss
.foo {
  animation: rotation 2s infinite linear;
  
  &:before {
    content: "\f36a";
    font-size: 100px;
    color: blue;
  }
}

@keyframes rotation {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(359deg);
  }
}
```

![2020-12-24_13-24-32](https://user-images.githubusercontent.com/609623/103106612-af8fcc80-45eb-11eb-9fb6-642139529d1f.gif)
